#General settings for the Mimicked mod.
[thresholds]
	#How many milliseconds of no audio input before assuming the speaker is done talking.
	# Default: 400
	# Range: 1 ~ 9223372036854775807
	timeout = 400
	#How loud is non-silence.
	# Default: 800
	# Range: 0 ~ 32767
	amplitudeThreshold = 800
	#Portion of samples above threshold to consider the clip as non-silent.
	# Default: 0.05
	# Range: 0.0 ~ 1.0
	loudThreshold = 0.05
	#RMS threshold to consider the clip as non-silent.
	# Default: 500.0
	# Range: 0.0 ~ 1.7976931348623157E308
	rmsThreshold = 500.0

[recording]
	#The chance to record a player when they are speaking.
	# Default: 0.2
	# Range: 0.0 ~ 1.0
	recordingChance = 0.2
	#The chance of a clip being replaced by a new one when a new recording is made if clip storage is full.
	# Default: 0.2
	# Range: 0.0 ~ 1.0
	replacementChance = 0.2
	#Maximum size of a mimic clip in seconds.
	# Default: 10.0
	# Range: 1.0 ~ 100.0
	maxClipLength = 10.0
	#Maximum number of stored clips for each player.
	# Default: 15
	# Range: > 1
	maxClipStorage = 15

[playback]
	#How often should mimic events happen (on average) in minutes.
	# Default: 5.0
	# Range: 0.0 ~ 1.7976931348623157E308
	sparsity = 90.0
	#The chance of a clip being deleted after it is used. This is disabled during overdrive.
	# Default: 0.5
	# Range: 0.0 ~ 1.0
	deletionChance = 0.5
	#Disables hearing yourself.
	disableSelf = false
	#Disable client-side audio processing when connected to a server with the mod installed (recommended for quality).
	preferServerSide = true
	#A whitelist for possible entities to be the source of the mimicking. Note that mimicking can only be done if there is a proper host nearby.
	#Add the entity's id to the list. An example list: ["minecraft:zombie", "minecraft:piglin"]
	#You can also put an entry of "@modid" to whitelist all entities from a mod. Example: ["@mimicked"]
	hostWhitelist = []

	#Overdrive is an event that occurs when a player is near an overdrive host, making mimicking and distorted mimicking happen much more often. During overdrive, deletion is disabled.
	[playback.overdrive]
		#A list of entities that when near a player, will turn mimicking into overdrive. This list is independent of the host whitelist.
		#Add the entity's id to the list. An example list: ["minecraft:zombie", "minecraft:piglin"]
		#You can also put an entry of "@modid" to whitelist all entities from a mod. Example: ["@mimicked"]
		overdriveHosts = []
		#How how often should mimic events happen (on average) in minutes when near an overdrive host is near a player. Deletion is disabled during overdrive.
		# Default: 0.2
		# Range: 0.0 ~ 1.7976931348623157E308
		overdrive = 90.0

[debug]
	#Enables debug logging.
	debug = false
